//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UT3ServerManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UT3ServerManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After server login, you can use ~ for entering commands:
        ///
        ///AdminLogin � Logs you in as an admin
        ///AdminLogout � Logs you out of admin mode
        ///AdminRestartMap � Restarts the current map
        ///AdminChangeMap � Loads a different map (gametype will change too, depending on map)
        ///Admin addbots &lt;#&gt; � Adds number of bots
        ///Admin killbots � Removes all bots
        ///AdminPlayerList � Shows PlayerID of players
        ///Adminkick � Kicks player from current game
        ///Adminkickban � Kicks player from current game and bans player from reconnectin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdminCommands {
            get {
                return ResourceManager.GetString("AdminCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any (legit or not) details for GameSpy or select LAN, otherwise you will not be able to connect to the server..
        /// </summary>
        internal static string LANPlay {
            get {
                return ResourceManager.GetString("LANPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Ports:
        ///
        ///6500 UDP (Query)
        ///6515 UDP (Dplay UDP)
        ///7777 UDP (UT Server Default)
        ///13000 UDP (Port for UT3)
        ///13139 UDP (Custom UDP Pings)
        ///27900 UDP (Master Server UDP Heartbeat)
        ///3783 TCP (Voice)
        ///6667 TCP (IRC)
        ///28900 TCP (Master Server List Request)
        ///29900 TCP (GP Connection Manager)
        ///29901 TCP (GP Search Manager)
        ///
        ///Additional Ports:
        ///
        ///6667 TCP ???
        ///8777 TCP|UDP ???
        ///9777 TCP|UDP ???
        ///8000 TCP|UDP (Webadmin)
        ///42292 TCP|UDP ???
        ///7777-7788 TCP|UDP ???
        ///27000-28000 TCP|UDP ???
        ///29900-29901 TCP|UDP ???
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PortInfo {
            get {
                return ResourceManager.GetString("PortInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsefulResources {
            get {
                return ResourceManager.GetString("UsefulResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ut3sm {
            get {
                object obj = ResourceManager.GetObject("ut3sm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
